import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <header className="p-4 border-b border-gray-200 dark:border-gray-800">
          <div className="container mx-auto">
            <h1 className="text-xl font-bold">Portfolio Product</h1>
          </div>
        </header>

        <main className="grow container mx-auto p-4">
          {children}
        </main>

        <footer className="p-4 border-t border-gray-200 dark:border-gray-800 text-center text-sm text-gray-500">
          <p>© 2024 Portfolio Product. Work in Progress.</p>
        </footer>
      </body>
    </html>
  );
}
